spring:
  datasource:
    url: jdbc:h2:mem:jwt_security
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true #http://localhost:8080/h2-console
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false